Repository SPACE-DEV-CLUB/SPACE_DEV_CLUB_FRONT, pull requests merged in 2022-02, with the labels that each got.

#105 ✨ add infinite scroll
  src/components/MyPage/Menus/Content.tsx
  src/components/MyPage/MyCard.tsx
  src/pages/search/index.tsx
  src/pages/tags/[tagname].tsx
Labels: Status: 머지 요청

#106 :lipstick: add footer, edit structure and more...
  public/image/ky_memoji.png
  public/image/logo-short-w.png
  public/image/logo-w.png
  src/components/Introduce/History.tsx
  src/components/Introduce/Intro.tsx
  src/components/Introduce/IntroFooter.tsx
  src/components/Introduce/Members.tsx
Labels: Status: 머지 요청

#107 🐛 fix inifinite loading
  src/components/MyPage/Menus/Content.tsx
Labels: Status: 머지 요청

#113 ✨add tags on mypage
  package.json
  src/components/MyPage/Menus/Content.tsx
  src/components/MyPage/Menus/ContentData.tsx
  src/hooks/useData.ts
  tsconfig.json
  yarn.lock
Labels: Status: 머지 요청

#115 🔥 불필요한 코드 삭제
  src/pages/_app.tsx
  src/styles/global-styles.ts
  src/styles/theme.tsx
Labels: Status: 머지 요청

#119 ✨ add tag filtering function
  src/components/Common/Tag.tsx
  src/components/MyPage/Menus/Content.tsx
  src/components/MyPage/Menus/ContentData.tsx
  src/components/MyPage/MyCard.tsx
  src/pages/tags/[tagname].tsx
Labels: Status: 머지 요청

#123 :sparkles: DarkMode toolBar 적용 및 Button Teme 추가
  src/components/Common/Button.tsx
  src/components/Editor/EditorContainer.tsx
  src/components/Editor/EditorInput/BottomMenu.tsx
  src/components/Editor/EditorInput/WriteHeader.tsx
  src/components/Editor/EditorInput/index.tsx
  src/components/Editor/EditorViewer/index.tsx
  src/components/Editor/SubmitModal/SubmitModal.tsx
  src/components/Editor/SubmitModal/index.tsx
  src/components/MyPage/Menus/Content.tsx
  src/styles/theme.tsx
Labels: Status: 머지 요청

#122 ⚡️ add blank page
  src/components/MyPage/Menus/BlankPage.tsx
  src/components/MyPage/Menus/ContentData.tsx
  src/components/MyPage/Menus/Series.tsx
Labels: Status: 머지 요청

#126 ✨ add large tag filtering
  .gitignore
  src/components/MyPage/Menus/Content.tsx
  src/components/MyPage/Menus/ContentData.tsx
  src/components/MyPage/MyCard.tsx
Labels: Status: 머지 요청

#128 ✨ connect data & infinite scroll to tag
  src/components/Common/ContentData.tsx
  src/components/MyPage/Menus/Content.tsx
  src/components/MyPage/Menus/ContentData.tsx
  src/pages/tags/[tagname].tsx
  src/pages/tags/index.tsx
Labels: Status: 머지 요청

#131 🐛 회원가입 후 페이지 전환
  src/components/SignUp/SignUp.tsx
Labels: Status: 리뷰 요청, Status: 머지 요청

#132 🐛 테스트 ID 변경 에러
  src/components/Details/DetailHeader.tsx
Labels: Status: 머지 요청

#133 :sparkles: add loading while checking our customer
  src/components/Common/Header.tsx
  src/components/Common/Loading.tsx
  src/components/SignUp/SignUp.tsx
  src/pages/loading.tsx
Labels: Status: 머지 요청

#135 ✨ 댓글 접기 기능, 정렬, UI, 리팩토링
  src/components/Details/ComComForm.tsx
  src/components/Details/Comment.tsx
  src/components/Details/CommentContainer.tsx
  src/components/Details/CommentForm.tsx
  src/components/Details/CommentFormContainer.tsx
  src/components/Details/CommentUser.tsx
  src/components/Details/DetailHeader.tsx
  src/pages/[id]/[details]/index.tsx
Labels: Status: 머지 요청

#158 ✨ dnd changed index series
  src/components/MyPage/Menus/Series.tsx
  src/components/MyPage/Series/DraggableItem.tsx
  src/components/MyPage/Series/SeriesContainer.tsx
  src/components/MyPage/Series/SeriesEditContainer.tsx
  src/components/SignUp/SignUp.tsx
  src/hooks/useData.ts
  src/pages/[id]/series/[title].tsx
  src/types/Main.ts
Labels: Status: 머지 요청

#159 ✨Strapi DB에서 댓글 삭제
  src/components/Details/Comment/Comment.tsx
  src/components/Details/Comment/DeleteModel.tsx
  src/components/Details/Comment/index.tsx
  src/styles/theme.tsx
Labels: Status: 머지 요청, deployed

#160 댓글과 대댓글 생성 및 삭제
  src/components/Details/Comment/CommentForm.tsx
  src/components/Details/Comment/CommentFormContainer.tsx
  src/components/Details/Comment/DeleteModel.tsx
  src/components/Details/Comment/ReCommentForm.tsx
Labels: Status: 머지 요청, deployed

#161 ✨ 시리즈에 무한스크롤 추가
  src/components/Common/CardLoading.tsx
  src/components/Common/ContentData.tsx
  src/components/Common/ErrorPage.tsx
  src/components/Common/Header.tsx
  src/components/Common/HeaderMenu.tsx
  src/components/Common/Loading.tsx
  src/components/Common/Modal.tsx
  src/components/Common/SkeletonLoading.tsx
  src/components/Layout/index.tsx
  src/components/MyPage/Intro.tsx
  src/components/MyPage/Menus/Content.tsx
  src/components/MyPage/Menus/SelfIntro.tsx
  src/components/MyPage/Menus/Series.tsx
  src/components/MyPage/Menus/index.ts
  src/components/MyPage/MyCard.tsx
  src/components/MyPage/Mymenu.tsx
  src/components/MyPage/Profile.tsx
  src/components/MyPage/Series/DetailCard.tsx
  src/components/MyPage/Series/DraggableItem.tsx
  src/components/MyPage/Series/SeriesCard.tsx
  src/components/MyPage/Series/SeriesContainer.tsx
  src/components/MyPage/Series/SeriesEditContainer.tsx
  src/components/MyPage/index.tsx
  src/components/Setting/CommonStyle.tsx
  src/components/Setting/ProfileSetting.tsx
  src/components/Setting/SettingForm.tsx
  src/components/Setting/SnsSetting.tsx
  src/components/Setting/VelogTitleSetting.tsx
  src/components/Tags/TagCardLoading.tsx
  src/pages/[id]/about/index.tsx
  src/pages/[id]/index.tsx
  src/pages/[id]/series/[title].tsx
  src/pages/[id]/series/index.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/loading.tsx
  src/pages/setting/index.tsx
  src/pages/signup.tsx
  src/pages/tags/[tagname].tsx
  src/pages/tags/index.tsx
Labels: Status: 머지 요청, deployed

#166 :sparkles: tooBarl decoBtn 기능 구현
  .vscode/settings.json
  src/components/Editor/EditorContainer.tsx
  src/components/Editor/EditorInput/ToolBar.tsx
  src/components/Editor/EditorInput/WriteForm.tsx
  src/components/Editor/EditorViewer/MDViewer.tsx
Labels: Status: 머지 요청

#169 Details/seriesbox
  src/components/Details/DetailHeader.tsx
  src/components/Details/SeriesContainer.tsx
  src/pages/[id]/[details]/index.tsx
  src/utils/date.ts
Labels: Status: 머지 요청, deployed

#171 :sparkles: h Tag 기능구현
  src/components/Editor/EditorContainer.tsx
Labels: Status: 머지 요청, deployed

#173 ✨상세 페이지 하단 시리즈 캐러샐에 데이터 연동
  src/components/Details/Carousel.tsx
  src/components/Details/Comment/Comment.tsx
  src/components/Details/Comment/CommentContainer.tsx
  src/components/Details/Comment/CommentForm.tsx
  src/components/Details/Comment/CommentFormContainer.tsx
  src/components/Details/Comment/DeleteModel.tsx
  src/components/Details/Comment/UpdateCommentForm.tsx
  src/components/Details/DetailCard.tsx
  src/components/Details/DetailHeader.tsx
  src/components/Details/LeftHeader.tsx
  src/components/Details/SeriesContainer.tsx
  src/pages/[id]/[details]/index.tsx
  src/types/Detail.ts
Labels: Status: 머지 요청, deployed

#174 ♻️ post 데이터 수정에 따른 코드 수정
  src/components/Details/LeftHeader.tsx
  src/pages/[id]/[details]/index.tsx
Labels: deployed

#177 ♻️ 시리즈 변경 시 좋아요 수 바뀌지 않던 버그 수정
  src/components/Details/LeftHeader.tsx
Labels: Status: 머지 요청, deployed

#178 ♻️ 같은 기능은 부모에서 생성 후 props로 넘겨주기
  src/components/Details/Carousel.tsx
  src/components/Details/Comment/CommentFormContainer.tsx
  src/components/Details/DetailCard.tsx
  src/components/Details/DetailHeader.tsx
  src/components/Details/LeftHeader.tsx
  src/components/Details/SeriesContainer.tsx
  src/pages/[id]/[details]/index.tsx
  src/types/Detail.ts
Labels: Status: 머지 요청, deployed

#179 :recycle: H 마크다운 버튼 utils 분리 및 함수 수정
  src/components/Editor/EditorContainer.tsx
  src/utils/tooBarHTag.ts
Labels: Status: 머지 요청, deployed

#180 :recycle: decoBtn utils 함수 분리
  src/components/Editor/EditorContainer.tsx
  src/utils/toolBarDeco.ts
  src/utils/toolBarHTag.ts
Labels: Status: 머지 요청, deployed

#181 ✨ 모달 추상화
  src/components/Common/Modal.tsx
  src/components/Details/Comment/DeleteModel.tsx
  src/components/Setting/SettingForm.tsx
Labels: Status: 머지 요청, deployed

#182 서치 관련 기능 추가
  src/components/Common/ContentData.tsx
  src/components/Common/Header.tsx
  src/components/MyPage/Menus/Content.tsx
Labels: Status: 머지 요청, deployed

#183 :sparkles: quote 기능 구현
  src/components/Editor/EditorContainer.tsx
  src/components/Editor/EditorInput/ToolBar.tsx
  src/components/Editor/EditorInput/WriteForm.tsx
  src/utils/toolBarCheckLine.ts
  src/utils/toolBarChkBtn.ts
Labels: Status: 머지 요청, deployed

#189 :truck: header 경로 통일을 위한 폴더명 수정
  src/pages/ write/index.tsx
Labels: Status: 머지 요청, deployed

#191 :truck: 폴더명 공백 제거
  src/pages/write/index.tsx
Labels: Status: 머지 요청, deployed

#192 ♻️ date.ts 로직 수정
  src/utils/date.ts
Labels: Status: 머지 요청, deployed

#193 ♻️ 이미지 변경
  public/image/error.png
  src/components/Common/ErrorPage.tsx
Labels: Status: 머지 요청, deployed

#194 ✨ 포스트 url 연결 및 기본 이미지 설정
  public/image/default_thumbnail.png
  public/image/스데브_로고_2차-n.png
  src/components/Details/DetailCard.tsx
  src/components/Home/CardContainer.tsx
  src/components/Home/ListCard.tsx
  src/components/Home/ListCardContainer.tsx
  src/components/Home/ListCardLoading.tsx
Labels: deployed

#199 :sparkles: add head
  src/pages/index.tsx
Labels: Status: 머지 요청, deployed
