Repository SPACE-DEV-CLUB/SPACE_DEV_CLUB_FRONT, pull requests merged in 2022-03, with the labels that each got.

#201 MDViewer 사용 및 정규 표현식으로 헤더 추출
  src/components/Details/DetailHeader.tsx
  src/components/Details/RightHeader.tsx
Labels: Status: 추가 기능 구현중, deployed

#202 ♻️ ListCard 좋아요 수 count 수정
  src/components/Home/ListCardContainer.tsx
Labels: Status: 머지 요청, deployed

#205 ♻️ 최신, 트렌딩 카드에 좋아요 수 추가
  src/components/Common/LoginErrorPage.tsx
  src/components/Home/CardContainer.tsx
  src/components/Home/Filter.tsx
  src/components/Home/ListCardContainer.tsx
  src/utils/date.ts
Labels: Status: 머지 요청, deployed

#206 자잘한 에러처리 및 버그 수정
  src/components/Details/Comment/CommentFormContainer.tsx
  src/components/Details/DetailHeader.tsx
  src/components/Details/LeftHeader.tsx
  src/components/Details/RightHeader.tsx
  src/components/Details/UDHashContainer.tsx
  src/pages/[id]/[details]/index.tsx
Labels: Status: 머지 요청, deployed

#209 :bug: search 뒤로가기 오류
  src/components/MyPage/MyCard.tsx
Labels: Status: 머지 요청, deployed

#210 :bug: block enter key
  src/components/Search/SearchBar.tsx
Labels: Status: 머지 요청, deployed

#211 개인 정보 고려 및 모달 컴포넌트 사용. 각종 리팩토링.
  src/components/Details/Comment/Comment.tsx
  src/components/Details/Comment/CommentContainer.tsx
  src/components/Details/Comment/CommentFormContainer.tsx
  src/components/Details/Comment/DeleteModel.tsx
  src/components/Details/Comment/index.tsx
  src/pages/[id]/[details]/index.tsx
Labels: Status: 머지 요청, deployed

#213 💄 CardContainer, Filter, Header 반응형 조건 max-width로 통일
  src/components/Home/CardContainer.tsx
  src/components/Home/Filter.tsx
  src/components/Home/ListCardContainer.tsx
Labels: Status: 머지 요청, deployed

#214 공유하기 기능 추가
  package.json
  public/image/kakao.png
  src/components/Details/LeftHeader.tsx
  src/pages/[id]/[details]/index.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  yarn.lock
Labels: Status: 머지 요청, deployed

#216 mainpage 리팩토링 및 post type 업데이트
  src/components/Home/CardContainer.tsx
  src/components/Home/ListCardContainer.tsx
  src/types/Main.ts
Labels: deployed

#217 스켈레톤 로딩 추가 및 LeftHeader 리팩터링
  src/components/Details/DetailHeader/Carousel.tsx
  src/components/Details/DetailHeader/DetailHeader.tsx
  src/components/Details/DetailHeader/SeriesContainer.tsx
  src/components/Details/DetailHeader/UDHashContainer.tsx
  src/components/Details/DetailHeader/index.ts
  src/components/Details/LeftHeader/LeftHeader.tsx
  src/components/Details/LeftHeader/Share.tsx
  src/components/Details/LeftHeader/index.ts
  src/components/Details/index.ts
  src/pages/[id]/[details]/index.tsx
Labels: Status: 머지 요청, deployed

#207 :sparkles: 링크 모달 세팅
  src/components/Editor/EditorContainer.tsx
  src/components/Editor/EditorInput/LinkInputModal.tsx
  src/components/Editor/EditorInput/ToolBar.tsx
  src/components/Editor/EditorInput/WriteForm.tsx
Labels: Status: 머지 요청, deployed

#219 🐛 header와 intro 에러 수정 및 프롭스 변경
  src/components/Common/Header.tsx
  src/components/Common/HeaderMenu.tsx
  src/components/Common/Loading.tsx
  src/components/Editor/EditorContainer.tsx
  src/components/MyPage/Intro.tsx
  src/components/MyPage/Menus/Series.tsx
  src/pages/[id]/[details]/index.tsx
Labels: Status: 머지 요청, deployed

#220 포스트 썸네일 없을 경우 레이아웃 설정, 메인페이지 메뉴옵션 수정
  src/components/Home/ListCard.tsx
  src/components/Home/Notice.tsx
Labels: Status: 머지 요청, deployed

#221 ✨ 포스트 상세페이지 meta tag 추가, 각종 버그 수정
  src/components/Details/LeftHeader/LeftHeader.tsx
  src/pages/[id]/[details]/index.tsx
  src/types/Detail.ts
Labels: Status: 추가 기능 구현중, deployed

#222 상세 페이지 공유 안되는것 해결 및 커스텀
  src/components/Details/LeftHeader/Share.tsx
  src/pages/[id]/[details]/index.tsx
Labels: Status: 머지 요청, deployed

#223 마이페이지 자기 소개 UI 및 기능 구현
  next.config.js
  package.json
  src/components/MyPage/Menus/SelfIntro.tsx
  src/components/MyPage/Menus/Series.tsx
  src/components/MyPage/Menus/WrappedEditor.tsx
  src/pages/[id]/[details]/index.tsx
  src/pages/_app.tsx
  src/styles/theme.tsx
  yarn.lock
Labels: Status: 머지 요청, deployed

#225 :bug: fix search link
  src/components/Common/Tag.tsx
  src/components/MyPage/MyCard.tsx
  src/components/Search/SearchFilter.tsx
Labels: Status: 머지 요청, deployed

#227 ✨게시글 삭제 및 게시글에 달린 댓글과 대댓글 삭제
  src/components/Details/Comment/CommentContainer.tsx
  src/components/Details/DetailHeader/UDHashContainer.tsx
Labels: Status: 머지 요청, deployed

#231 ♻️ 메인페이지 desc 없는 포스트 content 대체
  src/components/Details/DetailCard.tsx
  src/components/Home/CardContainer.tsx
  src/components/Home/ListCard.tsx
  src/components/Home/ListCardContainer.tsx
  src/types/Detail.ts
Labels: Status: 머지 요청, deployed

#232 목차 클릭 시 해당 위치로 스크롤 이동 및 스타일 적용
  src/components/Details/Comment/CommentFormContainer.tsx
  src/components/Details/DetailHeader/SeriesContainer.tsx
  src/components/Details/DetailHeader/UDHashContainer.tsx
  src/components/Details/RightHeader.tsx
  src/pages/[id]/[details]/index.tsx
  src/styles/global-styles.ts
Labels: Status: 머지 요청, deployed

#241 ♻️ mainpage style props 구조분해할당
  src/components/Home/Filter.tsx
  src/components/Home/Notice.tsx
  src/components/Home/SelectBox.tsx
Labels: Status: 머지 요청, deployed

#242 🐛 한글 URL 인코딩 되어 게시글을 찾지 못하는 오류 해결
  src/pages/[id]/[details]/index.tsx
Labels: Status: 머지 요청, deployed

#239 :sparkles: submit 전송 완료시 메인페이지로 이동 및 Header 새글작성 버튼 링크 추가
  src/components/Common/Header.tsx
  src/components/Editor/EditorContainer.tsx
Labels: Status: 머지 요청, deployed

#244 비공개 게시글 사용자 권한에 따른 조건 수정
  src/components/Common/ContentData.tsx
  src/components/Home/ListCardContainer.tsx
  src/components/MyPage/Menus/Content.tsx
  src/components/MyPage/MyCard.tsx
  src/components/Search/SearchFilter.tsx
  src/components/SignUp/SignUp.tsx
  src/pages/search/index.tsx
Labels: Status: 머지 요청, deployed

#245 ♻️ 좋아요 기능 수정, 트렌딩 좋아요 순 정렬
  src/components/Details/LeftHeader/LeftHeader.tsx
  src/components/Home/CardContainer.tsx
  src/components/Home/ListCard.tsx
Labels: Status: 머지 요청, deployed

#246 ✨ useReadingData 최근 읽은 포스트 hook 생성
  src/components/Details/DetailHeader/DetailHeader.tsx
  src/components/Home/ListCard.tsx
  src/hooks/useReadingData.ts
  src/types/Main.ts
Labels: Status: 머지 요청, deployed

#247 :sparkles: infoPost 및 url 작성된 글에 맞게 기본 값 추가 및 value chk 추가현
  src/components/Editor/EditorContainer.tsx
  src/components/Editor/SubmitModal/SubmitModal.tsx
Labels: Status: 머지 요청, deployed
