Repository SPACE-DEV-CLUB/SPACE_DEV_CLUB_FRONT, pull requests merged in 2022-01, with the labels that each got.

#4 상세 페이지의 상단 설계
  src/components/Details/DetailHeader.tsx
  src/components/Details/LeftHeader.tsx
  src/components/Details/RightHeader.tsx
  src/components/Details/SeriesContainer.tsx
  src/components/Details/UDHashContainer.tsx
  src/pages/details/index.tsx
  src/styles/globals.css
Labels: enhancement

#15 ➕ add icon dependency
  package-lock.json
  package.json
  src/components/MyPage/Intro.tsx
  yarn.lock
Labels: Status: 도움 요청

#23 ✨Carousel 설계 (이전, 다음 글)
  src/components/Details/Carousel.tsx
  src/components/Details/DetailHeader.tsx
  src/pages/details/index.tsx
Labels: Status: 리뷰 요청

#34 :lipstick: update constants
  src/components/Details/Carousel.tsx
  src/components/Details/Comment.tsx
  src/components/Details/CommentUser.tsx
  src/components/Details/LeftHeader.tsx
  src/components/Details/SeriesContainer.tsx
  src/components/Details/UDHashContainer.tsx
  src/components/Editor/BottomMenu.tsx
  src/components/Editor/EditForm.tsx
  src/components/Home/Card.tsx
  src/components/MyPage/Header.tsx
  src/components/MyPage/HeaderMenu.tsx
  src/components/MyPage/Intro.tsx
  src/components/MyPage/Menus/Content.tsx
  src/components/MyPage/Menus/SelfIntro.tsx
  src/components/MyPage/Mymenu.tsx
  src/constants/index.ts
  src/styles/theme.tsx
Labels: Status: 머지 요청

#44 💄 update constants
  src/constants/index.ts
Labels: Status: 머지 요청

#48 :lipstick: mainpage 카드 컴포넌트 변수 설정 및 태그 변경
  src/components/Home/Card.tsx
Labels: Status: 머지 요청

#43 :lipstick: edit color code, refactor styled-component
  src/components/MyPage/Header.tsx
  src/components/MyPage/MyCard.tsx
  src/components/MyPage/Series/DetailCard.tsx
  src/components/MyPage/Series/SeriesCard.tsx
  src/components/Search/SearchBar.tsx
  src/constants/index.ts
  src/pages/search/index.tsx
Labels: Status: 머지 요청

#60 Editor/structure
  src/components/Common/Tag.tsx
  src/components/Editor/EditorContainer.tsx
  src/components/Editor/MDViewer.tsx
  src/components/Editor/WriteHeader.tsx
  src/components/Editor/editor.module.css
  src/pages/editor/index.tsx
  src/styles/global-styles.ts
Labels: Status: 머지 요청

#67 ✨ upgrade series
  src/components/MyPage/Series/DetailCard.tsx
  src/components/MyPage/Series/SeriesContainer.tsx
  src/components/MyPage/Series/SeriesEditContainer.tsx
  src/constants/index.ts
  src/types/Main.ts
Labels: Status: 머지 요청

#70 ♻️ Emotion 리팩토링 및 다크모드 적용
  src/components/Details/Carousel.tsx
  src/components/Details/Comment.tsx
  src/components/Details/CommentUser.tsx
  src/components/Details/LeftHeader.tsx
  src/components/Details/SeriesContainer.tsx
  src/components/Details/UDHashContainer.tsx
  src/pages/details/index.tsx
Labels: Status: 머지 요청

#76 Home/modify header
  public/image/스데브로고_drakmode.png
  src/components/Home/Header.tsx
  src/components/Home/index.tsx
  src/pages/index.tsx
  src/pages/list/liked/index.tsx
  src/pages/list/read/index.tsx
  src/pages/recent/index.tsx
Labels: Status: 머지 요청

#78 ⚡️ add useData
  src/components/Common/Header.tsx
  src/components/MyPage/Menus/Content.tsx
  src/components/MyPage/MyCard.tsx
  src/components/MyPage/Series/SeriesEditContainer.tsx
  src/hooks/useData.ts
  src/utils/fetcher.ts
Labels: Status: 머지 요청

#75 :zap: dnd 퍼포먼스 개선, 리팩토링
  src/components/MyPage/Series/DraggableItem.tsx
  src/components/MyPage/Series/SeriesEditContainer.tsx
Labels: Status: 수정 요청

#79 💄 change series ui
  src/components/MyPage/Series/DraggableItem.tsx
  src/components/MyPage/Series/SeriesEditContainer.tsx
Labels: Status: 리뷰 요청

#82 :sparkles: MDviewer 스타일기능 구현
  public/favicon.ico
  src/components/Editor/MDViewer.tsx
  src/pages/_app.tsx
  src/styles/editor-styles.ts
  src/styles/global-styles.ts
  src/styles/globals.css
  src/styles/theme.tsx
Labels: Status: 머지 요청

#86 ✨ add tag page
  src/components/Common/Header.tsx
  src/components/Common/Tag.tsx
  src/components/Details/Carousel.tsx
  src/components/Details/CommentUser.tsx
  src/components/Details/SeriesContainer.tsx
  src/components/Details/UDHashContainer.tsx
  src/components/MyPage/MyCard.tsx
  src/components/Tags/TagCards.tsx
  src/constants/index.ts
  src/data/index.ts
  src/pages/index.tsx
  src/pages/tags/[tagname].tsx
  src/pages/tags/index.tsx
  src/types/Main.ts
Labels: Status: 머지 요청

#90 ♻️ refactor mypages
  src/components/Common/CardLoading.tsx
  src/components/Common/Header.tsx
  src/components/MyPage/Intro.tsx
  src/components/MyPage/Menus/Content.tsx
  src/components/MyPage/Menus/SelfIntro.tsx
  src/components/Tags/TagLoading.tsx
  src/components/Tags/TagMainLoading.tsx
  src/pages/tags/[tagname].tsx
Labels: Status: 머지 요청

#92 ✨ add CardLoading component
  src/components/Common/CardLoading.tsx
  src/components/Common/Header.tsx
  src/components/Tags/TagLoading.tsx
  src/styles/editor-styles.ts
  src/styles/loading-styled.ts
Labels: Status: 머지 요청

#94 ✨ add tag main skeleton loading
  src/components/Tags/TagCardLoading.tsx
  src/components/Tags/TagMainLoading.tsx
  src/pages/tags/[tagname].tsx
  src/pages/tags/index.tsx
Labels: Status: 머지 요청

#97 ✨상세 페이지의 404 페이지
  src/components/Details/ErrorPage.tsx
  src/pages/[id]/[details]/index.tsx
Labels: Status: 머지 요청
